# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Flameshot.Flameshot
PackageVersion: 13.2.0
PackageLocale: en-US
Publisher: flameshot-org
PublisherUrl: https://flameshot.org/
PublisherSupportUrl: https://flameshot.org/docs
PackageName: Flameshot
PackageUrl: https://flameshot.org/
License: GPL-3.0
LicenseUrl: https://github.com/flameshot-org/flameshot/blob/HEAD/LICENSE
CopyrightUrl: https://github.com/flameshot-org/flameshot/blob/master/LICENSE
ShortDescription: Powerful yet simple to use screenshot software.
Moniker: flameshot
Tags:
- capture
- screenshot
- snipping
ReleaseNotes: |-
  What's Changed
  This release mostly has bug fixes. This has an improvement (but not final fix) for mixed DPI screens from #4169. Please be patient as we work towards a final fix.
  - Minor RPM spec file tweaks by @pointydev in #4166
  - Grab color shortcut rebase by @borgmanJeremy in #4164
  - Adding sha to all builds by @borgmanJeremy in #4190
  - Fix translator memory leak by @borgmanJeremy in #4179
  - Added hash to CI builds by @borgmanJeremy in #4202
  - Fix screen positions in multi-monitor configuration when devicePixelRatio is other than one by @panpuchkov in #4169
  - Resolve translation conflicts by @borgmanJeremy in #4218
  - Windows CLI copy (fix for #4118) by @ElTh0r0 in #4211
  - Fix CI cmake issue on macOS by @borgmanJeremy in #4227
  - Remove color set on widget hide by @borgmanJeremy in #4226
  - Fix Appveyor by @borgmanJeremy in #4245
  - Add UI language selection by @ElTh0r0 in #4249
  - Add masked icon for macOS that adapts to light/dark backgrounds by @artptr in #4257
  - Introduce some exit codes (#3321) by @guyueshui in #4121
  - Show keyboard shortcut in the tray icon menu by @artptr in #4258
  - Fix typo in comment in GlobalShortcutFilter by @AmanChaturvedi24 in #4274
  - Fix memory leak in guiMutexLock() function by @avineet4 in #4277
  - Added libkf6guiaddons-dev as a Debian dependency by @SASHAKT1290 in #4304
  Translation-related
  - Translations update from Hosted Weblate by @weblate in #4170
  - Refresh translations for weblate by @borgmanJeremy in #4199
  - Translations update from Hosted Weblate by @weblate in #4219
  - Translations update from Hosted Weblate by @weblate in #4229
  - Translations update from Hosted Weblate by @weblate in #4234
  - Add missing translation files by @borgmanJeremy in #4244
  - Refreshed translation files by @borgmanJeremy in #4248
  - Translations update from Hosted Weblate by @weblate in #4250
  - Translations update from Hosted Weblate by @weblate in #4256
  - Translations update from Hosted Weblate by @weblate in #4262
  - Translations update from Hosted Weblate by @weblate in #4266
  - Translations update from Hosted Weblate by @weblate in #4275
  - Translations update from Hosted Weblate by @weblate in #4305
  - Translations update from Hosted Weblate by @weblate in #4309
  New Contributors
  - @pointydev made their first contribution in #4166
  - @artptr made their first contribution in #4257
  - @AmanChaturvedi24 made their first contribution in #4274
  - @avineet4 made their first contribution in #4277
  - @SASHAKT1290 made their first contribution in #4304
  Full Changelog: v13.1.0...v13.2.0
ReleaseNotesUrl: https://github.com/flameshot-org/flameshot/releases/tag/v13.2.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
