# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Flameshot.Flameshot
PackageVersion: 13.2.0
InstallerLocale: en-US
InstallerType: wix
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- bmp
- jpg
- png
ProductCode: '{5D698690-B818-4A89-B54B-6C3A7BDB4E8A}'
ReleaseDate: 2025-10-25
AppsAndFeaturesEntries:
- ProductCode: '{5D698690-B818-4A89-B54B-6C3A7BDB4E8A}'
  UpgradeCode: '{26D8062A-66D9-48D9-8924-42090FB9B3F9}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Flameshot'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/flameshot-org/flameshot/releases/download/v13.2.0/Flameshot-13.2.0-win64.msi
  InstallerSha256: 48A977F2D290D01EE37CDC9C4330DD06784277CB44EBD2741DFEC0DB192C279A
ManifestType: installer
ManifestVersion: 1.10.0
