# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Qalculate.Qalculate
PackageVersion: 5.8.1
PackageLocale: en-US
Publisher: Hanna Knutsson
PublisherUrl: https://qalculate.github.io/
PublisherSupportUrl: https://github.com/Qalculate/libqalculate/issues
Author: Hanna Knutsson
PackageName: Qalculate!
PackageUrl: https://qalculate.github.io/
License: GPL-2.0
LicenseUrl: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
ShortDescription: A highly versatile desktop calculator, with support for units, physical constants, uncertainty propagation, symbolic calculations, etc.
Description: |-
  Qalculate! is a multi-purpose cross-platform desktop calculator.
  It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation).
  Features include a large library of customizable functions, unit calculations and conversion, physical constants, symbolic calculations (including integrals and equations), arbitrary precision, uncertainty propagation, interval arithmetic, plotting, and a user-friendly interface (GTK, Qt, and CLI).
Moniker: qalculate
Tags:
- algebra
- calculator
- currencies
- engineering
- math
- physics
- units
ReleaseNotes: |-
  Qalculate! is a multi-purpose cross-platform desktop calculator. It is simple to use but provides power and versatility normally reserved for complicated math packages, as well as useful tools for everyday needs (such as currency conversion and percent calculation). Features include a large library of customizable functions, unit calculations and conversion, symbolic calculations (including integrals and equations), arbitrary precision, uncertainty propagation, interval arithmetic, plotting, and a user-friendly interface (Gtk, Qt, and CLI).
  Changes:
  - Show error when function or variable disabled by "--disable-insecure" is used
  - New completion method with matches selectable from numbered list
  - Configurable completion
  - Improve interpretation of function expressions with x, y, or z in object names (e.g. "x year"), or within quotation marks
  - Fix compilation with -fsanitize=undefined
  - Fix make check with --disable-insecure
  - Fix infinite loop during factorization on Windows
  - Fix crash after factorization or in RPN mode, with calculate-as-you-type enabled
  - Fix unable to write preferences because of missing configuration directory
  - Fixes for character encodings other than UTF-8
  - Minor bug fixes and feature enhancements
  Download the source code here:
  libqalculate-5.8.1.tar.gz
  Download the source code for the graphical user interfaces (qalculate-gtk and qalculate-qt) here:
  qalculate-gtk-5.8.1.tar.gz
  qalculate-qt-5.8.1.tar.gz
  Download Windows binaries here:
  64-bit installer
  64-bit zip (unpack and run without further installation; no application data are read or written outside of the unpacked directory)
  The binaries requires Windows 10 (1809) or later. They can also be installed using the Windows Package Manager (winget).
  GNU/Linux binaries:
  flatpak packages (recommended) are available at https://flathub.org/apps/details/io.github.Qalculate.qalculate-qt (Qt GUI) and https://flathub.org/apps/details/io.github.Qalculate (GTK GUI).
  A snap package are available at https://snapcraft.io/qalculate (GTK GUI).
  64-bit (x86) self-contained binaries (GTK GUI) (extract and run from anywhere on most GNU/Linux distributions; no translations included)
  For more information visit the website at http://qalculate.github.io/.
ReleaseNotesUrl: https://github.com/Qalculate/libqalculate/releases/tag/v5.8.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/Qalculate/libqalculate/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
