# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Qalculate.Qalculate
PackageVersion: 5.8.1
InstallerLocale: und
InstallerType: msi
Scope: machine
ProductCode: '{D2030C8A-4BB6-4997-B465-EC2D9218561E}'
ReleaseDate: 2025-10-27
AppsAndFeaturesEntries:
- ProductCode: '{D2030C8A-4BB6-4997-B465-EC2D9218561E}'
  UpgradeCode: '{FF701B51-D4D4-45FA-904A-D78F3960FB44}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Qalculate/libqalculate/releases/download/v5.8.1/qalculate-5.8.1-x64.msi
  InstallerSha256: D532315116FC3743BF947705C23000E977C44A0F5FEECA9DB6DB27DF2CB64BA4
ManifestType: installer
ManifestVersion: 1.10.0
